site_name: "Watcher"
site_description: "Documentation technique et opérationnelle de l'atelier Watcher"
site_url: "https://francis18georges-png.github.io/Watcher/"
repo_url: "https://github.com/francis18georges-png/Watcher"
edit_uri: "edit/main/docs/"
strict: true

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-night
        name: Passer en mode sombre
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Passer en mode clair
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - content.code.copy
    - content.code.annotate
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - docs
        - .
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
        - name: plantuml
          class: plantuml
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.plantuml:
      server: https://www.plantuml.com/plantuml

plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/francis18georges-png/Watcher
      name: Dépôt GitHub Watcher

nav:
  - Accueil: index.md
  - Quickstart sans commande: quickstart-sans-commande.md
  - Architecture:
      - Résumé express: architecture-summary.md
      - Vue d'ensemble: architecture.md
      - Arborescence cible: arborescence-cible.md
      - Journal de conception:
          - 2025-09-12: journal/2025-09-12.md
          - 2025-09-14: journal/2025-09-14.md
          - 2025-09-19: journal/2025-09-19.md
  - Sécurité et conformité:
      - Modèle de menaces: threat-model.md
      - Vérification des artefacts: security_provenance.md
      - Charte éthique: ethics.md
  - Gestion des releases:
      - Notes de version: release_notes.md
      - Guide hors-ligne: offline_guide.md
  - Exploitation:
      - Gouvernance du consentement: policy-consent.md
      - Conventions de logging: logging.md
      - Autopilote: autopilot.md
      - Autostart sans commande: autostart.md
      - Vérifier les artefacts: verifier-artefacts.md
      - Dépannage plug-and-play: depannage.md
      - Plan de tests pytest: tests-plan.md
      - Feuille de route: ROADMAP.md
      - Journal des modifications: CHANGELOG.md
      - Politique de fusion: merge-policy.md

extra_javascript:
  - https://unpkg.com/mermaid@10.9.1/dist/mermaid.min.js
