name: Discussion architecture & support
description: Poser une question sur l'architecture, le design ou l'utilisation de Watcher.
title: "[Discussion]: "
labels:
  - status:needs-triage
  - type:discussion
discussion_category_name: Support & architecture
body:
  - type: markdown
    attributes:
      value: |
        Utilisez ce modèle pour recueillir l'avis de la communauté ou valider une approche avant d'ouvrir une Pull Request.
        Consultez également `docs/merge-policy.md` pour connaître la signification des labels appliqués lors du tri.
  - type: dropdown
    id: scope
    attributes:
      label: Zone concernée
      description: Identifier la zone de code ou de documentation concernée facilite l'assignation des CODEOWNERS.
      options:
        - scope:app — Interface ou API utilisateur
        - scope:ml — Pipelines de données ou d'entraînement
        - scope:docs — Documentation, guides ou métriques
        - scope:ops — CI/CD, packaging ou scripts
        - scope:quality — Tests automatisés et qualité
        - scope:security — Configuration sensible, secrets, permissions
        - Non déterminé / Autre
  - type: textarea
    id: question
    attributes:
      label: Sujet
      description: Décrivez la question principale ou le point de décision.
      placeholder: "Quel module dois-je étendre pour ... ?"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Contexte
      description: Précisez ce que vous avez déjà essayé et fournissez les liens utiles.
  - type: textarea
    id: proposal
    attributes:
      label: Pistes envisagées
      description: Si vous avez une solution en tête, décrivez-la ici.
