blank_issues_enabled: false
contact_links:
  - name: Documentation QA
    url: https://github.com/WatcherOrg/Watcher/blob/main/QA.md
    about: Consultez la check-list QA avant d'ouvrir un ticket.
  - name: Guide des labels et des revues
    url: https://github.com/WatcherOrg/Watcher/blob/main/docs/merge-policy.md
    about: Résumé du workflow de tri, des labels et de l'automerge.
