name: Demande de fonctionnalité
description: Proposer une amélioration ou une nouvelle fonctionnalité.
title: "[Feature]: "
labels:
  - status:needs-triage
  - type:feature
body:
  - type: markdown
    attributes:
      value: |
        Merci de détailler la valeur ajoutée pour les utilisateurs ainsi que les impacts potentiels. Consultez `docs/merge-policy.md` pour comprendre comment votre demande sera triée et labellisée (statuts, portée et déclenchement de `status:queued-for-merge`).
  - type: dropdown
    id: scope
    attributes:
      label: Zone impactée
      description: Sélectionnez la zone fonctionnelle principale liée à la demande.
      options:
        - scope:app-experience — Interface ou API utilisateur, packaging client
        - scope:data-insights — Pipelines de données, entraînement ou modèles ML
        - scope:documentation — Documentation, guides ou métriques
        - scope:platform — CI/CD, infrastructure développeur ou scripts
        - scope:quality — Tests automatisés et qualité
        - scope:security — Configuration sensible, secrets, permissions
        - Non déterminé / Autre
  - type: checkboxes
    id: impact
    attributes:
      label: Alignement
      options:
        - label: Cette demande respecte les objectifs décrits dans `docs/ROADMAP.md`.
        - label: J'ai vérifié qu'aucune issue ouverte ne couvre déjà ce besoin.
          required: true
  - type: textarea
    id: summary
    attributes:
      label: Description
      description: Expliquez la proposition et le problème sous-jacent.
      placeholder: "En tant qu'utilisateur, je voudrais..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution proposée
      description: Détaillez l'approche technique ou UX pressentie.
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: Mentionnez les autres options étudiées et pourquoi elles n'ont pas été retenues.
  - type: textarea
    id: additional
    attributes:
      label: Contexte supplémentaire
      description: Ajouter des liens, maquettes, références ou contraintes.
