version: 2
autostart: true
offline_default: true
require_corroboration: 2
kill_switch_file: "~/.watcher/disable"
network_windows:
  - days: [mon, tue, wed, thu, fri, sat, sun]
    start: "02:00"
    end: "04:00"
budgets:
  bandwidth_mb_per_day: 200
  cpu_percent_cap: 60
  ram_mb_cap: 4096
allowlist_domains:
  - docs.python.org
  - pytorch.org
  - w3.org
subject:
  hostname: "{{ hostname }}"
  generated_at: "{{ generated_at }}"
models:
  llm:
    name: demo-smollm-135m-instruct.Q4_K_M.gguf
    sha256: 43d2819fb6bb94f514f4f099263b4526a65293fee7fdcbec8d3f12df0d48529f
    license: Apache-2.0
  embedding:
    name: demo-all-MiniLM-L6-v2.tar.gz
    sha256: a5a51b533681a69446283e3c6ce7c35bc098e0bd540c9ff56931a02c414dc054
    license: Apache-2.0
