name: ready-to-merge
on:
  pull_request_target:
    types: [labeled, opened, synchronize]

jobs:
  automerge:
    name: Merge PR when label is ready
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      checks: read
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Merge if ready-to-merge and checks passed
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge
          label: status:ready-to-merge
