name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Sync data
        run: dvc pull
        continue-on-error: true
      - name: Run lint
        run: make lint
      - name: Run type check
        run: make type
      - name: Run security checks
        run: |
          bandit -q -r . -c bandit.yml
          semgrep --quiet --error --config config/semgrep.yml .
      - name: Run tests
        run: make test

