name: CI

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black ruff pytest mypy bandit semgrep
      - name: Lint
        run: ruff check .
      - name: Format check
        run: black --check .
      - name: Type check
        run: mypy .
      - name: Bandit
        run: bandit -q -r .
      - name: Semgrep
        run: semgrep --quiet --error --config config/semgrep.yml .
      - name: Tests
        run: pytest -q

