name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish-windows-installer:
    name: Publish signed Windows installer
    runs-on: windows-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Validate SemVer tag
        shell: pwsh
        run: |
          if (-not ($env:GITHUB_REF_NAME -match '^v\d+\.\d+\.\d+$')) {
            Write-Error "Release tag '$env:GITHUB_REF_NAME' must match vMAJOR.MINOR.PATCH"
          }

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: Install build dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build Windows executable
        shell: pwsh
        run: pyinstaller packaging/watcher.spec --noconfirm

      - name: Package installer archive
        shell: pwsh
        run: |
          $archive = "dist/Watcher-Setup.zip"
          if (Test-Path $archive) {
            Remove-Item $archive
          }
          Compress-Archive -Path "dist/Watcher/*" -DestinationPath $archive

      - name: Sign release artifact
        uses: sigstore/gh-action@v2.1.1
        with:
          artifact: dist/Watcher-Setup.zip
          bundle: dist/Watcher-Setup.zip.sigstore

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Watcher ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            dist/Watcher-Setup.zip
            dist/Watcher-Setup.zip.sigstore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
